### ISSUE TITLE
Error by upgrading to Laravel 5.4

### ISSUE THREAD

**Issue by GertTimmerman** [OFFLINE-GmbH/persistent-settings#1]
When i do a upgrade to Laravel 5.4, i get an error:

`Call to undefined method Illuminate\Foundation\Application::share()`

The Laravel Upgrade Docs says:
"The share method has been removed from the container. This was a legacy method that has not been documented in several years. If you are using this method, you should begin using the  singleton method instead"

In the SettingsServiceProvider, the share method must be replaced by the following code:
```
$this->app->singleton('settings', function ($app) {
        $config = $app->config->get('settings', [
            'cache_file' => storage_path('settings.json'),
            'db_table'   => 'settings'
        ]);

        return new Settings($app['db'], new Cache($config['cache_file']), $config);
});
```

**Comment by tobias-kuendig** [comment]
Released as v1.0.3. Thanks!
